Replace solps_total_radiated_power() with make_solps_emitter() and remove SOLPSTotalRadiatedPower
cherab/solps pull request #52
Opened 2021-07-03 17:49 UTC by vsnever

This PR replaces `solps_total_radiated_power()` with a more general `make_solps_emitter()` and removes redundant `SOLPSTotalRadiatedPower`, because in `make_solps_emitter()` a combination of `RadiationFunction` and `VolumeTransform` is used instead. A script that demonstrates the usage of `make_solps_emitter()` on the example of total radiated power is added.

This fixes #50.

2021-07-22 12:05 UTC, jacklovell requested changes
This looks good to me @vsnever. I only have a couple of very minor changes to request in the demo script to make it a bit easier to follow. The way you've implemented things I think is good.

It's interesting that there's such a large performance improvement doing it this way: I get a factor ~40 speedup compared with the simpler "image plasma" demo. The same models are being evaluated in both cases, but I expect this demo uses more cached evaluations of the model because the AxisymmetricMapper doesn't cache values (x, y, z) which map to the same (r, z).

2021-07-22 12:05 UTC, jacklovell commented on demos/generomak_raw_files_solps_emitter.py
> +    return total_radiation
Since this function is only every called once in this demo, I think it makes more sense just to inline it. The narrative in the demo will flow better that way, otherwise users have to skip over this function when they first start reading the demo and then jump back up to it later on.

2021-07-22 12:05 UTC, jacklovell commented on demos/generomak_raw_files_solps_emitter.py
> +sim.total_radiation = total_radiation  # this creates sim.total_radiation_f2d and sim.total_radiation_f3d
I would move this above the creation of the camera, as it's more closely related to building the SOLPSSimullation / plasma object than it is actually doing the imaging of said object.

2021-07-22 18:38 UTC, vsnever commented
Hi @jacklovell, thanks for the review. I improved the demo as you suggested. Also, I set the `display_unsaturated_fraction` parameter of `PowerPipeline2D` to 0.9999 to prevent underexposure that can occur in case of poor ray statistics.

2021-07-22 18:38 UTC, vsnever commented on demos/generomak_raw_files_solps_emitter.py
> +    return total_radiation
Done.

2021-07-22 18:38 UTC, vsnever commented on demos/generomak_raw_files_solps_emitter.py
> +sim.total_radiation = total_radiation  # this creates sim.total_radiation_f2d and sim.total_radiation_f3d
Done.

2021-07-23 08:09 UTC, jacklovell approved these changes

2021-07-23 08:10 UTC, merged